### ISSUE TITLE
java.lang.IllegalArgumentException: Argument 0 for @NotNull parameter of com/intellij/openapi/actionSystem/DataKey.getData must not be null

### ISSUE THREAD

**Issue by dkandalov** [dkandalov/pomodoro-tm#2]
Error during dispatching of java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=ru.greeneyes.project.pomidoro.PomodoroComponent$UserNotifier$2@17b2595,notifier=null,catchExceptions=false,when=1358158416840] on sun.awt.windows.WToolkit@9a702b: Argument 0 for @NotNull parameter of com/intellij/openapi/actionSystem/DataKey.getData must not be null
java.lang.IllegalArgumentException: Argument 0 for @NotNull parameter of com/intellij/openapi/actionSystem/DataKey.getData must not be null
    at com.intellij.openapi.actionSystem.DataKey.getData(DataKey.java)
    at ru.greeneyes.project.pomidoro.PomodoroComponent$UserNotifier$2.run(PomodoroComponent.java:196)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:721)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:682)
    at java.awt.EventQueue$3.run(EventQueue.java:680)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:691)
    at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:673)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:498)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:333)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:244)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:163)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:151)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:147)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:139)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:97)

**Comment by dkandalov** [comment]
+1
Argument for @NotNull parameter 'dataContext' of com/intellij/openapi/actionSystem/DataKey.getData must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'dataContext' of com/intellij/openapi/actionSystem/DataKey.getData must not be null
	at com.intellij.openapi.actionSystem.DataKey.getData(DataKey.java)
	at ru.greeneyes.project.pomidoro.PomodoroComponent$UserNotifier$2.run(PomodoroComponent.java:196)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:577)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
