### ISSUE TITLE
"pomodoro.StartOrStopPomodoro' must override `getActionUpdateThread()"

### ISSUE THREAD

**Issue by dps999** [dkandalov/pomodoro-tm#27]
Hello,
this issue happens in Rider 2024.2.6

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'pomodoro.StartOrStopPomodoro' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: Pomodoro-tm]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

**Comment by dkandalov** [comment]
Hi. Thank you for reporting this.
It happened to few plugins, I guess this is a new way Jetbrains are trying to enforce deprecated APIs 🙄 
I'll fix it and upload a new version hopefully this week.

**Comment by dkandalov** [comment]
This should be fixed in plugin version 0.80.
